<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    
    <ItemGroup>
        <!-- Submodules -->
        <ProjectReference Include="..\..\submodules\mathematics\src\Hypercube.Mathematics\Hypercube.Mathematics.csproj" />
        <ProjectReference Include="..\..\submodules\utilities\src\Hypercube.Utilities\Hypercube.Utilities.csproj" />

        <!-- Analyzers -->
        <ProjectReference Include="..\..\submodules\utilities\src\Hypercube.Utilities.Analyzers\Hypercube.Utilities.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\..\submodules\utilities\src\Hypercube.Utilities.Analyzers.CodeFix\Hypercube.Utilities.Analyzers.CodeFix.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Silk.NET.GLFW" Version="2.22.0" />
        <PackageReference Include="Silk.NET.SDL" Version="2.23.0" />
    </ItemGroup>
    
</Project>
